# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            İlker Çakır
tagline:          'Portfolio'
description:      'Software Developer Portfolio & Blog'
url:              https://cakirilker.com/hyde
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

collections:
  - experiences

# Custom vars
repository: cakirilker/hyde
blog:
  url: https://blog.cakirilker.com/