version: '3.1'
services:
  jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --incremental
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_UID=1001
      - JEKYLL_GID=1001
      - JEKYLL_ENV=docker
      - VIRTUAL_HOST=cakirilker.com,www.cakirilker.com
      - VIRTUAL_PORT=4000